//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicProject.ImageServiceSoap {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ImageServiceSoap.ImageServiceSoap")]
    public interface ImageServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем binary_array из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveImage", ReplyAction="*")]
        ClinicProject.ImageServiceSoap.SaveImageResponse SaveImage(ClinicProject.ImageServiceSoap.SaveImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaveImage", ReplyAction="*")]
        System.Threading.Tasks.Task<ClinicProject.ImageServiceSoap.SaveImageResponse> SaveImageAsync(ClinicProject.ImageServiceSoap.SaveImageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем file_path из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadImage", ReplyAction="*")]
        ClinicProject.ImageServiceSoap.LoadImageResponse LoadImage(ClinicProject.ImageServiceSoap.LoadImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadImage", ReplyAction="*")]
        System.Threading.Tasks.Task<ClinicProject.ImageServiceSoap.LoadImageResponse> LoadImageAsync(ClinicProject.ImageServiceSoap.LoadImageRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем file_path из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveImage", ReplyAction="*")]
        ClinicProject.ImageServiceSoap.RemoveImageResponse RemoveImage(ClinicProject.ImageServiceSoap.RemoveImageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RemoveImage", ReplyAction="*")]
        System.Threading.Tasks.Task<ClinicProject.ImageServiceSoap.RemoveImageResponse> RemoveImageAsync(ClinicProject.ImageServiceSoap.RemoveImageRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveImage", Namespace="http://tempuri.org/", Order=0)]
        public ClinicProject.ImageServiceSoap.SaveImageRequestBody Body;
        
        public SaveImageRequest() {
        }
        
        public SaveImageRequest(ClinicProject.ImageServiceSoap.SaveImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] binary_array;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string format_string;
        
        public SaveImageRequestBody() {
        }
        
        public SaveImageRequestBody(byte[] binary_array, string format_string) {
            this.binary_array = binary_array;
            this.format_string = format_string;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClinicProject.ImageServiceSoap.SaveImageResponseBody Body;
        
        public SaveImageResponse() {
        }
        
        public SaveImageResponse(ClinicProject.ImageServiceSoap.SaveImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SaveImageResult;
        
        public SaveImageResponseBody() {
        }
        
        public SaveImageResponseBody(string SaveImageResult) {
            this.SaveImageResult = SaveImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadImage", Namespace="http://tempuri.org/", Order=0)]
        public ClinicProject.ImageServiceSoap.LoadImageRequestBody Body;
        
        public LoadImageRequest() {
        }
        
        public LoadImageRequest(ClinicProject.ImageServiceSoap.LoadImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string file_path;
        
        public LoadImageRequestBody() {
        }
        
        public LoadImageRequestBody(string file_path) {
            this.file_path = file_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClinicProject.ImageServiceSoap.LoadImageResponseBody Body;
        
        public LoadImageResponse() {
        }
        
        public LoadImageResponse(ClinicProject.ImageServiceSoap.LoadImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadImageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] LoadImageResult;
        
        public LoadImageResponseBody() {
        }
        
        public LoadImageResponseBody(byte[] LoadImageResult) {
            this.LoadImageResult = LoadImageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveImageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveImage", Namespace="http://tempuri.org/", Order=0)]
        public ClinicProject.ImageServiceSoap.RemoveImageRequestBody Body;
        
        public RemoveImageRequest() {
        }
        
        public RemoveImageRequest(ClinicProject.ImageServiceSoap.RemoveImageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveImageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string file_path;
        
        public RemoveImageRequestBody() {
        }
        
        public RemoveImageRequestBody(string file_path) {
            this.file_path = file_path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveImageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveImageResponse", Namespace="http://tempuri.org/", Order=0)]
        public ClinicProject.ImageServiceSoap.RemoveImageResponseBody Body;
        
        public RemoveImageResponse() {
        }
        
        public RemoveImageResponse(ClinicProject.ImageServiceSoap.RemoveImageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class RemoveImageResponseBody {
        
        public RemoveImageResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ImageServiceSoapChannel : ClinicProject.ImageServiceSoap.ImageServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ImageServiceSoapClient : System.ServiceModel.ClientBase<ClinicProject.ImageServiceSoap.ImageServiceSoap>, ClinicProject.ImageServiceSoap.ImageServiceSoap {
        
        public ImageServiceSoapClient() {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ImageServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinicProject.ImageServiceSoap.SaveImageResponse ClinicProject.ImageServiceSoap.ImageServiceSoap.SaveImage(ClinicProject.ImageServiceSoap.SaveImageRequest request) {
            return base.Channel.SaveImage(request);
        }
        
        public string SaveImage(byte[] binary_array, string format_string) {
            ClinicProject.ImageServiceSoap.SaveImageRequest inValue = new ClinicProject.ImageServiceSoap.SaveImageRequest();
            inValue.Body = new ClinicProject.ImageServiceSoap.SaveImageRequestBody();
            inValue.Body.binary_array = binary_array;
            inValue.Body.format_string = format_string;
            ClinicProject.ImageServiceSoap.SaveImageResponse retVal = ((ClinicProject.ImageServiceSoap.ImageServiceSoap)(this)).SaveImage(inValue);
            return retVal.Body.SaveImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClinicProject.ImageServiceSoap.SaveImageResponse> ClinicProject.ImageServiceSoap.ImageServiceSoap.SaveImageAsync(ClinicProject.ImageServiceSoap.SaveImageRequest request) {
            return base.Channel.SaveImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClinicProject.ImageServiceSoap.SaveImageResponse> SaveImageAsync(byte[] binary_array, string format_string) {
            ClinicProject.ImageServiceSoap.SaveImageRequest inValue = new ClinicProject.ImageServiceSoap.SaveImageRequest();
            inValue.Body = new ClinicProject.ImageServiceSoap.SaveImageRequestBody();
            inValue.Body.binary_array = binary_array;
            inValue.Body.format_string = format_string;
            return ((ClinicProject.ImageServiceSoap.ImageServiceSoap)(this)).SaveImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinicProject.ImageServiceSoap.LoadImageResponse ClinicProject.ImageServiceSoap.ImageServiceSoap.LoadImage(ClinicProject.ImageServiceSoap.LoadImageRequest request) {
            return base.Channel.LoadImage(request);
        }
        
        public byte[] LoadImage(string file_path) {
            ClinicProject.ImageServiceSoap.LoadImageRequest inValue = new ClinicProject.ImageServiceSoap.LoadImageRequest();
            inValue.Body = new ClinicProject.ImageServiceSoap.LoadImageRequestBody();
            inValue.Body.file_path = file_path;
            ClinicProject.ImageServiceSoap.LoadImageResponse retVal = ((ClinicProject.ImageServiceSoap.ImageServiceSoap)(this)).LoadImage(inValue);
            return retVal.Body.LoadImageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClinicProject.ImageServiceSoap.LoadImageResponse> ClinicProject.ImageServiceSoap.ImageServiceSoap.LoadImageAsync(ClinicProject.ImageServiceSoap.LoadImageRequest request) {
            return base.Channel.LoadImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClinicProject.ImageServiceSoap.LoadImageResponse> LoadImageAsync(string file_path) {
            ClinicProject.ImageServiceSoap.LoadImageRequest inValue = new ClinicProject.ImageServiceSoap.LoadImageRequest();
            inValue.Body = new ClinicProject.ImageServiceSoap.LoadImageRequestBody();
            inValue.Body.file_path = file_path;
            return ((ClinicProject.ImageServiceSoap.ImageServiceSoap)(this)).LoadImageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClinicProject.ImageServiceSoap.RemoveImageResponse ClinicProject.ImageServiceSoap.ImageServiceSoap.RemoveImage(ClinicProject.ImageServiceSoap.RemoveImageRequest request) {
            return base.Channel.RemoveImage(request);
        }
        
        public void RemoveImage(string file_path) {
            ClinicProject.ImageServiceSoap.RemoveImageRequest inValue = new ClinicProject.ImageServiceSoap.RemoveImageRequest();
            inValue.Body = new ClinicProject.ImageServiceSoap.RemoveImageRequestBody();
            inValue.Body.file_path = file_path;
            ClinicProject.ImageServiceSoap.RemoveImageResponse retVal = ((ClinicProject.ImageServiceSoap.ImageServiceSoap)(this)).RemoveImage(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClinicProject.ImageServiceSoap.RemoveImageResponse> ClinicProject.ImageServiceSoap.ImageServiceSoap.RemoveImageAsync(ClinicProject.ImageServiceSoap.RemoveImageRequest request) {
            return base.Channel.RemoveImageAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClinicProject.ImageServiceSoap.RemoveImageResponse> RemoveImageAsync(string file_path) {
            ClinicProject.ImageServiceSoap.RemoveImageRequest inValue = new ClinicProject.ImageServiceSoap.RemoveImageRequest();
            inValue.Body = new ClinicProject.ImageServiceSoap.RemoveImageRequestBody();
            inValue.Body.file_path = file_path;
            return ((ClinicProject.ImageServiceSoap.ImageServiceSoap)(this)).RemoveImageAsync(inValue);
        }
    }
}
